### ISSUE TITLE
READMEの手順の修正

### ISSUE THREAD

**Issue by petitroto** [tktkbohshi/fairseq-jp-dialog-api#2]
READMEにある依存パッケージのインストールコマンドが違うみたいです。

これを
`$ pip install -m requirements.txtでライブラリをインストールしてください．`
↓
こうすると動きました。
`$ pip install -r requiremments.txtでライブラリをインストールしてください．`

* オプションは-mではなく-r？
* ファイル名にtypo

手順を直すのかファイル名を直すのかあると思うのでPRではなくIssueでご連絡します。

**Comment by tktkbohshi** [comment]
私のTypoですね。すみません
修正しておきます。ありがとうございます

**Comment by petitroto** [comment]
修正ありがとうございます！
ファイル名の方も直す必要があると思うので宜しくお願いします。

**Comment by tktkbohshi** [comment]
たびたびすみません．ファイル名も修正しました
